// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/chat.proto

package go_micro_srv_chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UsersRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersRequest) Reset()         { *m = UsersRequest{} }
func (m *UsersRequest) String() string { return proto.CompactTextString(m) }
func (*UsersRequest) ProtoMessage()    {}
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{0}
}
func (m *UsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersRequest.Unmarshal(m, b)
}
func (m *UsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersRequest.Marshal(b, m, deterministic)
}
func (dst *UsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersRequest.Merge(dst, src)
}
func (m *UsersRequest) XXX_Size() int {
	return xxx_messageInfo_UsersRequest.Size(m)
}
func (m *UsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersRequest proto.InternalMessageInfo

func (m *UsersRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersResponse) Reset()         { *m = UsersResponse{} }
func (m *UsersResponse) String() string { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()    {}
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{1}
}
func (m *UsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResponse.Unmarshal(m, b)
}
func (m *UsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResponse.Marshal(b, m, deterministic)
}
func (dst *UsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResponse.Merge(dst, src)
}
func (m *UsersResponse) XXX_Size() int {
	return xxx_messageInfo_UsersResponse.Size(m)
}
func (m *UsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResponse proto.InternalMessageInfo

func (m *UsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type RoomsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomsRequest) Reset()         { *m = RoomsRequest{} }
func (m *RoomsRequest) String() string { return proto.CompactTextString(m) }
func (*RoomsRequest) ProtoMessage()    {}
func (*RoomsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{2}
}
func (m *RoomsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomsRequest.Unmarshal(m, b)
}
func (m *RoomsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomsRequest.Marshal(b, m, deterministic)
}
func (dst *RoomsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomsRequest.Merge(dst, src)
}
func (m *RoomsRequest) XXX_Size() int {
	return xxx_messageInfo_RoomsRequest.Size(m)
}
func (m *RoomsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomsRequest proto.InternalMessageInfo

func (m *RoomsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoomsResponse struct {
	Rooms                []*Room  `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomsResponse) Reset()         { *m = RoomsResponse{} }
func (m *RoomsResponse) String() string { return proto.CompactTextString(m) }
func (*RoomsResponse) ProtoMessage()    {}
func (*RoomsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{3}
}
func (m *RoomsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomsResponse.Unmarshal(m, b)
}
func (m *RoomsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomsResponse.Marshal(b, m, deterministic)
}
func (dst *RoomsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomsResponse.Merge(dst, src)
}
func (m *RoomsResponse) XXX_Size() int {
	return xxx_messageInfo_RoomsResponse.Size(m)
}
func (m *RoomsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomsResponse proto.InternalMessageInfo

func (m *RoomsResponse) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type JoinRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{4}
}
func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (dst *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(dst, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JoinRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type JoinResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{5}
}
func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (dst *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(dst, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

type OutRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutRequest) Reset()         { *m = OutRequest{} }
func (m *OutRequest) String() string { return proto.CompactTextString(m) }
func (*OutRequest) ProtoMessage()    {}
func (*OutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{6}
}
func (m *OutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutRequest.Unmarshal(m, b)
}
func (m *OutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutRequest.Marshal(b, m, deterministic)
}
func (dst *OutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutRequest.Merge(dst, src)
}
func (m *OutRequest) XXX_Size() int {
	return xxx_messageInfo_OutRequest.Size(m)
}
func (m *OutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OutRequest proto.InternalMessageInfo

func (m *OutRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OutRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type OutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutResponse) Reset()         { *m = OutResponse{} }
func (m *OutResponse) String() string { return proto.CompactTextString(m) }
func (*OutResponse) ProtoMessage()    {}
func (*OutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{7}
}
func (m *OutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutResponse.Unmarshal(m, b)
}
func (m *OutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutResponse.Marshal(b, m, deterministic)
}
func (dst *OutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutResponse.Merge(dst, src)
}
func (m *OutResponse) XXX_Size() int {
	return xxx_messageInfo_OutResponse.Size(m)
}
func (m *OutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OutResponse proto.InternalMessageInfo

type SendRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{8}
}
func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (dst *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(dst, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type SendResponse struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{9}
}
func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (dst *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(dst, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

type StreamRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LastCreated          int64    `protobuf:"varint,2,opt,name=last_created,json=lastCreated,proto3" json:"last_created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{10}
}
func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (dst *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(dst, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StreamRequest) GetLastCreated() int64 {
	if m != nil {
		return m.LastCreated
	}
	return 0
}

type StreamResponse struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{11}
}
func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (dst *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(dst, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

func (m *StreamResponse) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type Event struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Created              int64    `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{12}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Event) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Event) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Event) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type Room struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{13}
}
func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (dst *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(dst, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Room) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c3051a3975c1a444, []int{14}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*UsersRequest)(nil), "go.micro.srv.chat.UsersRequest")
	proto.RegisterType((*UsersResponse)(nil), "go.micro.srv.chat.UsersResponse")
	proto.RegisterType((*RoomsRequest)(nil), "go.micro.srv.chat.RoomsRequest")
	proto.RegisterType((*RoomsResponse)(nil), "go.micro.srv.chat.RoomsResponse")
	proto.RegisterType((*JoinRequest)(nil), "go.micro.srv.chat.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "go.micro.srv.chat.JoinResponse")
	proto.RegisterType((*OutRequest)(nil), "go.micro.srv.chat.OutRequest")
	proto.RegisterType((*OutResponse)(nil), "go.micro.srv.chat.OutResponse")
	proto.RegisterType((*SendRequest)(nil), "go.micro.srv.chat.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "go.micro.srv.chat.SendResponse")
	proto.RegisterType((*StreamRequest)(nil), "go.micro.srv.chat.StreamRequest")
	proto.RegisterType((*StreamResponse)(nil), "go.micro.srv.chat.StreamResponse")
	proto.RegisterType((*Event)(nil), "go.micro.srv.chat.Event")
	proto.RegisterType((*Room)(nil), "go.micro.srv.chat.Room")
	proto.RegisterType((*User)(nil), "go.micro.srv.chat.User")
}

func init() { proto.RegisterFile("proto/chat.proto", fileDescriptor_chat_c3051a3975c1a444) }

var fileDescriptor_chat_c3051a3975c1a444 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x51, 0x6b, 0xdb, 0x30,
	0x10, 0x8e, 0x63, 0x3b, 0xa3, 0x67, 0x27, 0x6c, 0x7a, 0xd8, 0x8c, 0xa1, 0x69, 0xaa, 0xa7, 0x32,
	0xa8, 0x37, 0xb2, 0xed, 0x71, 0x63, 0xac, 0x6c, 0x90, 0x31, 0x28, 0x73, 0xd9, 0x73, 0x71, 0x63,
	0xad, 0x35, 0xcc, 0x56, 0x26, 0xc9, 0x85, 0xfe, 0xce, 0xfd, 0xa1, 0x71, 0x92, 0xdc, 0xba, 0x44,
	0x0e, 0xcd, 0xdb, 0xe9, 0xee, 0xbb, 0xef, 0x3e, 0xc9, 0xdf, 0x19, 0x9e, 0x6f, 0x04, 0x57, 0xfc,
	0xcd, 0xfa, 0xa6, 0x50, 0x99, 0x0e, 0xc9, 0x8b, 0x6b, 0x9e, 0xd5, 0xd5, 0x5a, 0xf0, 0x4c, 0x8a,
	0xdb, 0x0c, 0x0b, 0x74, 0x0e, 0xf1, 0x2f, 0xc9, 0x84, 0xcc, 0xd9, 0xdf, 0x96, 0x49, 0x45, 0x66,
	0x30, 0xae, 0xca, 0xc4, 0x5b, 0x78, 0x27, 0x07, 0xf9, 0xb8, 0x2a, 0xe9, 0x27, 0x98, 0xda, 0xba,
	0xdc, 0xf0, 0x46, 0x32, 0x72, 0x0a, 0x61, 0x8b, 0x89, 0xc4, 0x5b, 0xf8, 0x27, 0xd1, 0xf2, 0x55,
	0xb6, 0xc5, 0x99, 0x61, 0x43, 0x6e, 0x50, 0xc8, 0x9f, 0x73, 0x5e, 0xef, 0xe2, 0xb7, 0xf5, 0x07,
	0x7e, 0x81, 0x89, 0x1d, 0xfc, 0xd8, 0x90, 0x1b, 0x14, 0xfd, 0x00, 0xd1, 0x77, 0x5e, 0x35, 0x03,
	0xf4, 0xe4, 0x25, 0x4c, 0x10, 0xb7, 0x2a, 0x93, 0xb1, 0xce, 0xd9, 0x13, 0x9d, 0x41, 0x6c, 0xda,
	0xcc, 0x54, 0xfa, 0x1e, 0xe0, 0xbc, 0x55, 0xfb, 0xb2, 0x4c, 0x21, 0xd2, 0x5d, 0x96, 0xe4, 0x23,
	0x44, 0x17, 0xac, 0x29, 0x3b, 0x96, 0x0c, 0x42, 0x76, 0xcb, 0x1a, 0xa5, 0x89, 0xa2, 0x65, 0xe2,
	0xb8, 0xc9, 0x57, 0xac, 0xe7, 0x06, 0x46, 0x4f, 0x21, 0x36, 0xed, 0xf6, 0x25, 0x0e, 0x01, 0x6a,
	0x26, 0x65, 0x71, 0xcd, 0x2e, 0xef, 0xd5, 0x1c, 0xd8, 0xcc, 0xaa, 0xa4, 0x5f, 0x60, 0x7a, 0xa1,
	0x04, 0x2b, 0xea, 0x21, 0xd5, 0xc7, 0x10, 0xff, 0x29, 0xa4, 0xba, 0x5c, 0x0b, 0x56, 0x28, 0x66,
	0xb4, 0xfb, 0x79, 0x84, 0xb9, 0x33, 0x93, 0xa2, 0x9f, 0x61, 0xd6, 0x71, 0xd8, 0xa1, 0xfb, 0x8a,
	0xae, 0x21, 0xd4, 0x67, 0x42, 0x20, 0x50, 0x77, 0x1b, 0x66, 0xe7, 0xeb, 0x18, 0x73, 0xbf, 0x05,
	0xaf, 0xed, 0xab, 0xe9, 0x18, 0x55, 0x2a, 0x9e, 0xf8, 0x46, 0xa5, 0xe2, 0x88, 0xb9, 0xe2, 0xe5,
	0x5d, 0x12, 0x18, 0x0c, 0xc6, 0x24, 0x81, 0x67, 0x9d, 0xe8, 0x50, 0x8b, 0xee, 0x8e, 0xf4, 0x35,
	0x04, 0xf8, 0xf5, 0xb7, 0xee, 0x4a, 0x20, 0x68, 0x8a, 0x9a, 0x75, 0x93, 0x30, 0x46, 0x2c, 0x3a,
	0xf1, 0x29, 0xd8, 0xe5, 0x3f, 0x1f, 0x82, 0xb3, 0x9b, 0x42, 0x91, 0x1f, 0x10, 0x6a, 0xbf, 0x93,
	0xa3, 0x01, 0x63, 0x77, 0x4e, 0x4e, 0x17, 0xc3, 0x00, 0xeb, 0x87, 0x11, 0xb2, 0x69, 0x77, 0x3b,
	0xd9, 0xfa, 0x7b, 0xe1, 0x64, 0x7b, 0xb4, 0x18, 0x74, 0x44, 0x56, 0x10, 0xa0, 0x69, 0xc9, 0xdc,
	0x81, 0xed, 0x2d, 0x41, 0x7a, 0x34, 0x58, 0xbf, 0xa7, 0xfa, 0x06, 0xfe, 0x79, 0xab, 0xc8, 0xa1,
	0x03, 0xf9, 0xb0, 0x07, 0xe9, 0x7c, 0xa8, 0xdc, 0x97, 0x84, 0x9e, 0x75, 0x4a, 0xea, 0xed, 0x82,
	0x53, 0x52, 0xdf, 0xec, 0x74, 0x44, 0x7e, 0xc2, 0xc4, 0x78, 0x91, 0xb8, 0xde, 0xe2, 0x91, 0xd5,
	0xd3, 0xe3, 0x1d, 0x88, 0x8e, 0xf0, 0xad, 0x77, 0x35, 0xd1, 0xbf, 0xbd, 0x77, 0xff, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x7f, 0x4c, 0x4b, 0xe6, 0x0a, 0x05, 0x00, 0x00,
}
